# ==============================================================================
# cdl_local.R -- Read CDL from a local bulk copy instead of the CropScape API.
#
# WHY
# CropScape is a public web service and behaves like one: the 347-field-year
# validation run took 52 minutes and could have failed at any request. The same
# 347 read from local rasters took 5.6 seconds. A published CDL year never
# changes, so downloading once per machine and reading a file thereafter is
# strictly better.
#
# WHAT IT DOES NOT CHANGE
# The numbers. Against the polygon's own geometric area on those 347
# field-years, local came in at +0.23% mean and the API at +0.06% -- both well
# inside 30 m pixel quantisation, and the two agreed on the dominant crop for
# 346 of 347 fields. The single disagreement was 33.0% against 32.7% between
# the top two classes, where neither answer is more correct than the other.
# Go local for reliability and speed.
#
# THE STORE
# Outside the repository so it can never be committed, and shared by every
# project on the machine. Set CDL_DIR to move it.
#
#   ~/geodata/cdl/national/   extracted national GeoTIFFs, one per year
#   ~/geodata/cdl/tif/        same, alternative name
#
# Populate it with python/download_cdl.py. CONUS only: Alaska and Hawaii ship
# as separate products and are not handled here.
# ==============================================================================

CDL_TIF_DIRS <- c("national", "tif")

# Pre-clipped CDL, one small GeoTIFF per field per year, keyed by the same
# geometry hash the rest of the cache uses.
#
# This is what makes the deployed Shiny app independent of CropScape. The
# national rasters are ~25 GB and cannot ship to shinyapps.io; a clip of one
# field for one year is a few kilobytes, so the whole demo library fits in the
# bundle with room to spare. Generated by r/make_cdl_clips.R from the national
# store; see that script for what it does and does not cover.
CDL_CLIPS_DIR <- function() {
  Sys.getenv("CDL_CLIPS", unset = file.path(PIPELINE_DIR, "cdl_clips"))
}

#' Path to a pre-made clip for this field and year, or NA.
cdl_clip_path <- function(aoi, year) {
  p <- file.path(CDL_CLIPS_DIR(), sprintf("%s_%d.tif", cache_key(aoi, "cdlclip"), year))
  if (file.exists(p)) p else NA_character_
}

#' Root of the local CDL store.
#'
#' Not path.expand("~"). On Windows R expands "~" to the user's Documents
#' folder, not their home directory, so the default silently pointed at
#' C:/Users/<name>/Documents/geodata and found nothing -- which looks exactly
#' like "no data downloaded" and sent every call back to the API. Python's
#' Path.home() and R's "~" disagree here, so the store the downloader writes
#' and the store the reader looks in must be resolved the same way.
cdl_home <- function() {
  if (.Platform$OS.type == "windows") {
    up <- Sys.getenv("USERPROFILE", unset = "")
    if (nzchar(up)) return(gsub("\\\\", "/", up))
  }
  path.expand("~")
}

cdl_root <- function() {
  Sys.getenv("CDL_DIR", unset = file.path(cdl_home(), "geodata", "cdl"))
}

#' Path to one year's national raster, or NA if it is not there.
cdl_year_tif <- function(year) {
  for (sub in CDL_TIF_DIRS) {
    hits <- list.files(file.path(cdl_root(), sub),
                       pattern = sprintf("^%d.*[.]tif$", year),
                       full.names = TRUE)
    hits <- hits[!grepl("[.]ovr[.]tif$", hits)]
    if (length(hits)) return(hits[1])
  }
  NA_character_
}

#' Does this file exist AND open AND read to its far corner?
#'
#' Dimensions come from the header, which is written early, so a truncated
#' raster reports a plausible size and only fails when the last block is read.
#' Checking here means the error arrives at the status check rather than
#' part-way through a long extraction.
cdl_readable <- function(path) {
  if (is.na(path) || !file.exists(path)) return(FALSE)
  tryCatch({
    r <- terra::rast(path)
    if (terra::nrow(r) < 1 || terra::ncol(r) < 1) return(FALSE)
    # Crop to the far corner and pull the values. terra::readValues() needs an
    # explicit readStart()/readStop() pair and returns nothing useful without
    # one, so a crop is both simpler and harder to get subtly wrong.
    e  <- terra::ext(r)
    rs <- terra::res(r)
    corner <- terra::ext(e$xmax - rs[1] * 256, e$xmax,
                         e$ymin, e$ymin + rs[2] * 256)
    v <- terra::values(terra::crop(r, corner))
    length(v) > 0
  }, error = function(e) FALSE)
}

#' Years present in the store and actually usable.
cdl_available_years <- function() {
  out <- integer(0)
  for (sub in CDL_TIF_DIRS) {
    fs <- list.files(file.path(cdl_root(), sub), pattern = "[.]tif$",
                     full.names = TRUE)
    fs <- fs[!grepl("[.]ovr[.]tif$", fs)]
    for (f in fs) {
      y <- suppressWarnings(as.integer(substr(basename(f), 1, 4)))
      if (!is.na(y) && !(y %in% out) && cdl_readable(f)) out <- c(out, y)
    }
  }
  sort(out)
}

#' Whether the pipeline should prefer the local store.
#'
#' On by default once any year is present, so the reliable path is what you get
#' without asking for it. FIELDRS_CDL_LOCAL=0 forces the API back.
# cdl_readable() opens and reads from every national raster it is given, which
# is far too expensive to repeat on each get_cdl() call. The store does not
# change while a session runs, so scan once and remember.
.cdl_years_cache <- new.env(parent = emptyenv())

cdl_available_years_cached <- function() {
  if (is.null(.cdl_years_cache$years)) {
    .cdl_years_cache$years <- cdl_available_years()
  }
  .cdl_years_cache$years
}

cdl_use_local <- function() {
  flag <- Sys.getenv("FIELDRS_CDL_LOCAL", unset = NA)
  if (!is.na(flag)) return(!flag %in% c("0", "false", "FALSE", ""))
  length(cdl_available_years_cached()) > 0 || dir.exists(CDL_CLIPS_DIR())
}

#' One year's CDL clipped to the field, read from the local store.
#'
#' Returns the same SpatRaster shape as get_cdl(), including the `touches =
#' FALSE` centre-in-polygon rule -- see cropland.R for why that matters.
get_cdl_local <- function(aoi, year, clip = TRUE) {
  # A pre-made clip answers without the national raster being present at all,
  # which is the case on shinyapps.io.
  cp <- cdl_clip_path(aoi, year)
  if (!is.na(cp)) {
    r <- terra::rast(cp)
    names(r) <- paste0("cdl_", year)
    return(r)
  }

  path <- cdl_year_tif(year)
  if (!cdl_readable(path)) {
    stop("No usable local CDL for ", year, " in ", cdl_root(),
         "\n  Run: python python/download_cdl.py --years ", year,
         "\n  Or set FIELDRS_CDL_LOCAL=0 to use the CropScape API.",
         call. = FALSE)
  }

  r <- terra::rast(path)
  # Some published years carry no projection tag at all. Left untagged, the
  # reprojected boundary lands nowhere near the raster and the read comes back
  # empty rather than failing, so state the known CRS instead of hoping.
  if (is.na(terra::crs(r)) || !nzchar(terra::crs(r))) {
    terra::crs(r) <- "EPSG:5070"
  }

  poly <- terra::project(terra::vect(sf::st_union(aoi)), terra::crs(r))
  r <- terra::crop(r, terra::ext(poly) + 30)     # one pixel of margin
  names(r) <- paste0("cdl_", year)
  if (clip) r <- terra::mask(r, poly, touches = FALSE)
  r
}
